version: "3.8"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=mydb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=admin
      - INFLUXDB_USER_PASSWORD=admin
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
