// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package messages

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	MessageID int32
	Topic     string
	Message   string
	CreatedAt pgtype.Timestamptz
}
